### PR TITLE
Adding an approximate distance value to the beacon analysis [WIP]

### PR DESCRIPTION
**Pull request by buggy213**
Formula comes from [here](http://photo.stackexchange.com/questions/12434/how-do-i-calculate-the-distance-of-an-object-in-a-photo). I haven't tested this yet, but I will as soon as possible.

### CODE REVIEW

**Comment by ehsanmasdar** [comment]
@buggy213 Awesome! Can you retarget this at the dev branch.

**Comment by ehsanmasdar** [comment]
@buggy213 Have you been able to test this?

**Comment by buggy213** [comment]
No, competition season has been incredibly busy but I will try to as soon as I can

**Comment by buggy213** [comment]
Yeah... this doesn't actually work that well. The issue is that the perceived size of the beacon fluctuates wildly from frame to frame. For now, I'll scrap this idea.

**Pull request closed without merging**
