### PR TITLE
Add beacon distance approximation

### PR DESCRIPTION
**Pull request by smo-key**

### CODE REVIEW

**Comment by smo-key** [comment]
@willfisher I get the distance data, but it's not really very accurate...

**Comment by willfisher** [comment]
I will try and work on it. I attached a good class with everything you
should need, that's not all mixed up with the rest of the vision code.

All you need to do is call the update method each frame and pass it the
height (in pixels, as it appears in the frame) of whatever reference object
on the beacon, or the beacon itself, you choose. Image a vertical line
going straight through the center of the beacon, the closer the reference
object is to that line (for example the height along the direct center of
the front of the beacon), the more accurate the distance will be. I also
think, but I'm not sure, that it is more accurate when the beacon is
centered on the frame; if so I can work on fixing that.

**Comment by willfisher** [comment]
Made a mistake on the file I sent earlier. Fixed class is attached.

**Comment by willfisher** [comment]
Oops this is very old, I just saw the close message. Anyways, if you ever work on it read above, here's the class: http://pastebin.com/kNaZSnJS

**Pull request closed without merging**
